import "~/styles/globals.css"

import { Provider } from "jotai"

import { ThemeProvider } from "./theme-provider"

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-Hans" suppressHydrationWarning className="h-full">
      <body className="h-full">
        <Provider>
          <ThemeProvider>{children}</ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
